import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { motion } from "framer-motion";
import {
  LineChart,
  Line,
  XAxis,
  YAxis,
  Tooltip,
  ResponsiveContainer,
  ReferenceArea,
  CartesianGrid,
} from "recharts";

import { AnimatedCard } from "@/components/AnimatedCard";
import { PageLoader } from "@/components/PageLoader";
import { ProgressRing } from "@/components/ProgressRing";
import { api } from "@/lib/api";
import { DOCTOR_REPORT_COST } from "@/lib/gameEngine";
import type { DayLog, GameState, UserProfile, WeeklyInsights } from "@/lib/types";

export const Route = createFileRoute("/insights")({
  head: () => ({ meta: [{ title: "Stats — GlycoBete" }] }),
  component: Insights,
});

function dateFromKey(key: string) {
  const [year, month, day] = key.split("-").map(Number);
  return new Date(year, month - 1, day);
}

function Insights() {
  const [loading, setLoading] = useState(true);
  const [insights, setInsights] = useState<WeeklyInsights | null>(null);
  const [modal, setModal] = useState<string | null>(null);
  const [days, setDays] = useState<DayLog[]>([]);
  const [game, setGame] = useState<GameState | null>(null);
  const [profile, setProfile] = useState<UserProfile | null>(null);
  const [healthScore, setHealthScore] = useState(0);

  useEffect(() => {
    (async () => {
      const [d, g, p, health] = await Promise.all([
        api.getLast7Days(),
        api.getGame(),
        api.getProfile(),
        api.getHealthDashboard(),
      ]);
      setDays(d);
      setGame(g);
      setProfile(p);
      setHealthScore(health.metrics.healthScore);
      const res = await api.analyzeWeek(
        d.map((day) => ({ date: day.date, fasting: day.fastingSugar, meals: day.meals.length })),
      );
      setInsights(res);
      setLoading(false);
    })();
  }, []);

  const pageLoading = loading || !game;

  const sugars = days.map((d) => d.fastingSugar).filter((n): n is number => n !== null);
  const avgSugar = sugars.length
    ? Math.round(sugars.reduce((s, n) => s + n, 0) / sugars.length)
    : 0;
  const mealsLogged = days.reduce((s, d) => s + d.meals.length, 0);
  const daysInRange = days.filter(
    (d) => d.fastingSugar && d.fastingSugar >= 70 && d.fastingSugar <= 140,
  ).length;

  const chartData = days.map((d) => {
    const date = dateFromKey(d.date);
    return {
      day: date.toLocaleDateString("en-US", { weekday: "short" }),
      sugar: d.fastingSugar,
    };
  });

  const generateReport = async () => {
    const spend = await api.spendCoins(DOCTOR_REPORT_COST);
    if (!spend.ok) {
      toast.error(`Need ${DOCTOR_REPORT_COST} coins. You have ${game.healthCoins}.`);
      return;
    }
    setGame(spend.game);
    await api.unlockAchievement("data_mage");
    const text = `GLYCOBETE PATIENT REPORT
========================
Name: ${profile?.name}
Type: ${profile?.diabetesType}
Period: Last 7 days

VITALS
- Average fasting sugar: ${avgSugar} mg/dL
- Days in target range (70-140): ${daysInRange}/7
- Meals logged: ${mealsLogged}

MEDICATIONS
${profile?.medications || "Not specified"}

AI-DETECTED PATTERNS
${insights?.weeklyNarrative ?? ""}

BEST DAY: ${insights?.bestDay ?? ""}
NEEDS WORK: ${insights?.worstDay ?? ""}

RECOMMENDATION
${insights?.topRecommendation ?? ""}

QUESTIONS FOR YOUR DOCTOR
- Is my fasting trend acceptable?
- Should we adjust medication timing?
- Any concerns with my meal pattern?

Generated by GlycoBete
`;
    setModal(text);
  };

  return (
    <PageLoader loading={pageLoading} message="Analyzing your stats..." minMs={1400}>
      {game && (
      <>
      <div className="max-w-4xl mx-auto p-4 md:p-8 space-y-5">
        <motion.div initial={{ opacity: 0, y: -10 }} animate={{ opacity: 1, y: 0 }}>
          <h1 className="font-display text-lg">YOUR STATS</h1>
          <p className="text-sm text-[var(--theme-muted)] mt-2">Last 7 days — daily, weekly trends.</p>
        </motion.div>

        <AnimatedCard>
          <div className="glass-card rounded-2xl p-6 flex flex-col md:flex-row items-center gap-6">
            <ProgressRing value={healthScore} label="HEALTH" sublabel="SCORE" />
            <div className="flex-1 grid grid-cols-2 gap-3 w-full">
              <Stat n={avgSugar || "—"} l="AVG FASTING" />
              <Stat n={game.streak} l="BEST STREAK" />
              <Stat n={mealsLogged} l="MEALS LOGGED" />
              <Stat n={`${daysInRange}/7`} l="DAYS IN RANGE" />
            </div>
          </div>
        </AnimatedCard>

        <AnimatedCard delay={0.1}>
        <div className="rounded-2xl border border-[var(--theme-border)] bg-[var(--theme-card)] p-6">
          <p className="font-display text-[10px] text-[var(--theme-accent)] mb-4">SUGAR THIS WEEK</p>
          <ResponsiveContainer width="100%" height={280}>
            <LineChart data={chartData}>
              <CartesianGrid strokeDasharray="3 3" stroke="#334155" />
              <XAxis dataKey="day" stroke="#94A3B8" style={{ fontFamily: "Inter" }} />
              <YAxis domain={[50, 250]} stroke="#94A3B8" style={{ fontFamily: "Inter" }} />
              <ReferenceArea y1={70} y2={140} fill="#22C55E" fillOpacity={0.15} label={{ value: "Target", position: "insideTopRight", fill: "#22C55E", fontSize: 10 }} />
              <ReferenceArea y1={140} y2={180} fill="#EAB308" fillOpacity={0.1} />
              <ReferenceArea y1={180} y2={250} fill="#EF4444" fillOpacity={0.1} />
              <Tooltip
                contentStyle={{
                  background: "#1E293B",
                  border: "1px solid #334155",
                  borderRadius: 12,
                }}
                labelStyle={{ color: "#F1F5F9" }}
                formatter={(value: number) => {
                  const status = value < 70 ? "🔵 Low" : value <= 140 ? "🟢 Normal" : value <= 180 ? "🟡 Caution" : "🔴 Danger";
                  return [`${value} mg/dL ${status}`, "Fasting"];
                }}
              />
              <Line
                type="monotone"
                dataKey="sugar"
                stroke="#F59E0B"
                strokeWidth={3}
                dot={{ r: 6, fill: "#F59E0B", strokeWidth: 2, stroke: "#1E293B" }}
                activeDot={{ r: 8, fill: "#F59E0B" }}
                connectNulls
              />
            </LineChart>
          </ResponsiveContainer>
          <div className="flex flex-wrap gap-4 mt-4 text-xs text-[var(--theme-muted)]">
            <span className="flex items-center gap-1"><span className="h-2 w-4 rounded bg-green-500/30" /> Normal (70–140)</span>
            <span className="flex items-center gap-1"><span className="h-2 w-4 rounded bg-yellow-500/30" /> Caution (140–180)</span>
            <span className="flex items-center gap-1"><span className="h-2 w-4 rounded bg-red-500/30" /> Danger (180+)</span>
          </div>
        </div>
        </AnimatedCard>

        {insights && (
          <div className="rounded-2xl border border-[var(--theme-cyan)] bg-[var(--theme-card-alt)] p-6">
            <p className="font-display text-[10px] text-[var(--theme-cyan)] mb-3">🤖 WEEKLY ANALYSIS</p>
            <p className="text-sm text-[var(--theme-fg)] leading-relaxed">{insights.weeklyNarrative}</p>
            <p className="mt-3 text-sm text-green-400">Best day: {insights.bestDay}</p>
            <p className="text-sm text-red-400">Needs work: {insights.worstDay}</p>
            <p className="mt-3 text-sm text-[var(--theme-accent)]">💡 {insights.topRecommendation}</p>
          </div>
        )}

        <div className="rounded-2xl border border-[var(--theme-border)] bg-[var(--theme-card)] p-5 text-center">
          <p className="font-display text-[10px]">GENERATE DOCTOR REPORT</p>
          <p className="text-xs text-[var(--theme-muted)] mt-1">
            (Costs 100 🪙 Health Coins — you have {game.healthCoins})
          </p>
          <button
            onClick={generateReport}
            className="mt-4 rounded-full bg-[var(--theme-accent)] px-6 py-3 font-display text-[10px] text-slate-900 hover:scale-105 active:scale-95 transition-all"
          >
            GENERATE
          </button>
        </div>
      </div>

      {modal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-[var(--theme-bg)]/90 p-4">
          <div className="bg-[var(--theme-card)] border border-[var(--theme-border)] rounded-2xl max-w-2xl w-full max-h-[80vh] flex flex-col">
            <div className="p-5 border-b border-[var(--theme-border)] flex justify-between">
              <h3 className="font-display text-xs">DOCTOR REPORT</h3>
              <button onClick={() => setModal(null)} className="text-[var(--theme-muted)]">
                ✕
              </button>
            </div>
            <pre className="p-5 overflow-auto text-xs text-[var(--theme-fg)] font-mono whitespace-pre-wrap flex-1">
              {modal}
            </pre>
            <div className="p-4 flex gap-3 border-t border-[var(--theme-border)]">
              <button
                onClick={() => {
                  navigator.clipboard.writeText(modal);
                  toast.success("Copied");
                }}
                className="flex-1 rounded-full bg-[var(--theme-primary)] px-4 py-3 font-display text-[10px] text-white"
              >
                COPY TEXT
              </button>
              <button
                onClick={() => setModal(null)}
                className="flex-1 rounded-full bg-[var(--theme-border)] px-4 py-3 font-display text-[10px] text-white"
              >
                CLOSE
              </button>
            </div>
          </div>
        </div>
      )}
      </>
      )}
    </PageLoader>
  );
}

function Stat({ n, l }: { n: number | string; l: string }) {
  return (
    <div className="rounded-2xl border border-[var(--theme-border)] bg-[var(--theme-card)] p-5 text-center">
      <p className="font-display text-2xl md:text-3xl text-[var(--theme-accent)]">{n}</p>
      <p className="mt-2 text-xs text-[var(--theme-muted)]">{l}</p>
    </div>
  );
}
