import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { AppShell } from "@/components/AppShell";
import { HeartLoading } from "@/components/HeartLoading";
import {
  storage,
  last7Days,
  bossProgress,
  DOCTOR_REPORT_COST,
  unlockAchievement,
} from "@/lib/gameEngine";
import { analyzeWeek } from "@/lib/geminiApi";
import type { WeeklyInsights } from "@/lib/types";
import {
  LineChart,
  Line,
  XAxis,
  YAxis,
  Tooltip,
  ResponsiveContainer,
  ReferenceArea,
  CartesianGrid,
} from "recharts";
import { toast } from "sonner";

export const Route = createFileRoute("/insights")({
  head: () => ({ meta: [{ title: "Stats — GlycoBete" }] }),
  component: Insights,
});

function dateFromKey(key: string) {
  const [year, month, day] = key.split("-").map(Number);
  return new Date(year, month - 1, day);
}

function Insights() {
  const [loading, setLoading] = useState(true);
  const [insights, setInsights] = useState<WeeklyInsights | null>(null);
  const [modal, setModal] = useState<string | null>(null);

  const days = last7Days();
  const sugars = days.map((d) => d.fastingSugar).filter((n): n is number => n !== null);
  const avgSugar = sugars.length
    ? Math.round(sugars.reduce((s, n) => s + n, 0) / sugars.length)
    : 0;
  const mealsLogged = days.reduce((s, d) => s + d.meals.length, 0);
  const daysInRange = days.filter(
    (d) => d.fastingSugar && d.fastingSugar >= 70 && d.fastingSugar <= 140,
  ).length;
  const game = storage.getGame();

  const chartData = days.map((d) => {
    const date = dateFromKey(d.date);
    return {
      day: date.toLocaleDateString("en-US", { weekday: "short" }),
      sugar: d.fastingSugar,
    };
  });

  useEffect(() => {
    (async () => {
      const res = await analyzeWeek(
        days.map((d) => ({ date: d.date, fasting: d.fastingSugar, meals: d.meals.length })),
      );
      setInsights(res);
      setLoading(false);
    })();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const generateReport = () => {
    if (game.healthCoins < DOCTOR_REPORT_COST) {
      toast.error(`Need ${DOCTOR_REPORT_COST} coins. You have ${game.healthCoins}.`);
      return;
    }
    game.healthCoins -= DOCTOR_REPORT_COST;
    storage.setGame(game);
    unlockAchievement("data_mage");
    const profile = storage.getProfile();
    const text = `GLYCOBETE PATIENT REPORT
========================
Name: ${profile?.name}
Type: ${profile?.diabetesType}
Period: Last 7 days

VITALS
- Average fasting sugar: ${avgSugar} mg/dL
- Days in target range (70-140): ${daysInRange}/7
- Meals logged: ${mealsLogged}

MEDICATIONS
${profile?.medications || "Not specified"}

AI-DETECTED PATTERNS
${insights?.weeklyNarrative ?? ""}

BEST DAY: ${insights?.bestDay ?? ""}
NEEDS WORK: ${insights?.worstDay ?? ""}

RECOMMENDATION
${insights?.topRecommendation ?? ""}

QUESTIONS FOR YOUR DOCTOR
- Is my fasting trend acceptable?
- Should we adjust medication timing?
- Any concerns with my meal pattern?

Generated by GlycoBete
`;
    setModal(text);
  };

  return (
    <AppShell>
      {loading && <HeartLoading />}
      <div className="max-w-4xl mx-auto p-4 md:p-8 space-y-5">
        <div>
          <h1 className="font-display text-lg">YOUR STATS</h1>
          <p className="text-sm text-slate-400 mt-2">Last 7 days of data.</p>
        </div>

        <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
          <Stat n={avgSugar || "—"} l="AVG FASTING" />
          <Stat n={game.streak} l="BEST STREAK" />
          <Stat n={mealsLogged} l="MEALS LOGGED" />
          <Stat n={daysInRange} l="DAYS IN RANGE" />
        </div>

        <div className="rounded-2xl border border-slate-700 bg-slate-800 p-6">
          <p className="font-display text-[10px] text-amber-400 mb-4">SUGAR THIS WEEK</p>
          <ResponsiveContainer width="100%" height={250}>
            <LineChart data={chartData}>
              <CartesianGrid strokeDasharray="3 3" stroke="#334155" />
              <XAxis dataKey="day" stroke="#94A3B8" style={{ fontFamily: "Inter" }} />
              <YAxis stroke="#94A3B8" style={{ fontFamily: "Inter" }} />
              <ReferenceArea y1={70} y2={140} fill="#22C55E" fillOpacity={0.1} />
              <Tooltip
                contentStyle={{
                  background: "#1E293B",
                  border: "1px solid #334155",
                  borderRadius: 12,
                }}
                labelStyle={{ color: "#F1F5F9" }}
              />
              <Line
                type="monotone"
                dataKey="sugar"
                stroke="#F59E0B"
                strokeWidth={3}
                dot={{ r: 5, fill: "#F59E0B" }}
                connectNulls
              />
            </LineChart>
          </ResponsiveContainer>
        </div>

        {insights && (
          <div className="rounded-2xl border border-cyan-700 bg-slate-700 p-6">
            <p className="font-display text-[10px] text-cyan-400 mb-3">🤖 WEEKLY ANALYSIS</p>
            <p className="text-sm text-slate-200 leading-relaxed">{insights.weeklyNarrative}</p>
            <p className="mt-3 text-sm text-green-400">Best day: {insights.bestDay}</p>
            <p className="text-sm text-red-400">Needs work: {insights.worstDay}</p>
            <p className="mt-3 text-sm text-amber-300">💡 {insights.topRecommendation}</p>
          </div>
        )}

        <div className="rounded-2xl border border-slate-700 bg-slate-800 p-5 text-center">
          <p className="font-display text-[10px]">GENERATE DOCTOR REPORT</p>
          <p className="text-xs text-slate-400 mt-1">
            (Costs 100 🪙 Health Coins — you have {game.healthCoins})
          </p>
          <button
            onClick={generateReport}
            className="mt-4 rounded-full bg-amber-500 px-6 py-3 font-display text-[10px] text-slate-900 hover:scale-105 active:scale-95 transition-all"
          >
            GENERATE
          </button>
        </div>
      </div>

      {modal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/90 p-4">
          <div className="bg-slate-800 border border-slate-700 rounded-2xl max-w-2xl w-full max-h-[80vh] flex flex-col">
            <div className="p-5 border-b border-slate-700 flex justify-between">
              <h3 className="font-display text-xs">DOCTOR REPORT</h3>
              <button onClick={() => setModal(null)} className="text-slate-400">
                ✕
              </button>
            </div>
            <pre className="p-5 overflow-auto text-xs text-slate-200 font-mono whitespace-pre-wrap flex-1">
              {modal}
            </pre>
            <div className="p-4 flex gap-3 border-t border-slate-700">
              <button
                onClick={() => {
                  navigator.clipboard.writeText(modal);
                  toast.success("Copied");
                }}
                className="flex-1 rounded-full bg-blue-600 px-4 py-3 font-display text-[10px] text-white"
              >
                COPY TEXT
              </button>
              <button
                onClick={() => setModal(null)}
                className="flex-1 rounded-full bg-slate-600 px-4 py-3 font-display text-[10px] text-white"
              >
                CLOSE
              </button>
            </div>
          </div>
        </div>
      )}
    </AppShell>
  );
}

function Stat({ n, l }: { n: number | string; l: string }) {
  return (
    <div className="rounded-2xl border border-slate-700 bg-slate-800 p-5 text-center">
      <p className="font-display text-2xl md:text-3xl text-amber-400">{n}</p>
      <p className="mt-2 text-xs text-slate-400">{l}</p>
    </div>
  );
}
